export const IPC = {
  chatSend: 'chat:send',
  chatThinking: 'chat:thinking',
  chatToolCall: 'chat:tool-call',
  chatMessage: 'chat:message',
  chatError: 'chat:error',
  chatPlaySound: 'chat:play-sound',
  rapportGet: 'rapport:get',
  rapportReset: 'rapport:reset',
  rapportChanged: 'rapport:changed',
  memoriesGet: 'memories:get',
  memoriesDelete: 'memories:delete',
  memoriesClear: 'memories:clear',
  settingsGet: 'settings:get',
  settingsSet: 'settings:set',
  mcpStatuses: 'mcp:statuses',
  mcpReload: 'mcp:reload',
  windowToggleAlwaysOnTop: 'window:toggle-always-on-top',
  windowOpenSettings: 'window:open-settings',
  windowGetPosition: 'window:get-position',
  windowSetPosition: 'window:set-position',
  logsOpenFolder: 'logs:open-folder',
  logsGetPath: 'logs:get-path',
  logsRendererError: 'logs:renderer-error'
} as const
